[package]
name = "cea-slides"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Gabriel Dos Santos <gabriel.dossantos@cea.fr"]
license = "CeCILL-C"
description = "Touying theme for crafting Typst presentations conforming with the CEA corporate identity"
repository = "https://github.com/dssgabriel/cea-slides.git"
keywords = ["touying", "presentation", "theme"]

compiler = "0.12.0"
exclude = ["*.pdf"]

[template]
path = "template"
entrypoint = "template.typ"
